<a href="https://colab.research.google.com/github/mohd-faizy/Probabilistic-Deep-Learning-with-TensorFlow/blob/main/00_The_TensorFlow_Probability_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

--- 
<strong> 
    <h1 align='center'>The TensorFlow Probability library</h1> 
</strong>

---

<p align='center'>
<a href=#></a></p>

<p align='center'>
  <a href="#"><img src='https://github.com/mohd-faizy/Probabilistic-Deep-Learning-with-TensorFlow/blob/main/Tensorflow_Dev_png/head.png?raw=true' alt="head"></a>
</p>

In [1]:
# Importing tensorflow probability library 
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions


## __a) Univariate distributions__

In [2]:
# Importing tensorflow probability library 
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

# Defining our first univariate distribution object
'''
Standard normal distribution with 0 mean and standard
deviation equal to 1
'''
normal = tfd.Normal(loc=0., scale=1.)
print(normal)

tfp.distributions.Normal("Normal", batch_shape=[], event_shape=[], dtype=float32)


In [3]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=0., scale=1.)
normal.sample()

<tf.Tensor: shape=(), dtype=float32, numpy=-0.8745248>

In [4]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=0., scale=1.)
normal.sample(3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.5690917 , -0.14160319, -0.6670809 ], dtype=float32)>

In [5]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=0., scale=1.)
normal.prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.35206532>

In [6]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=0., scale=1.)
normal.log_prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0439385>

In [7]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(probs=0.7)
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[], event_shape=[], dtype=int32)


In [8]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(logits=0.847)
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[], event_shape=[], dtype=int32)


In [9]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.sample(3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 1], dtype=int32)>

In [10]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.prob(1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.69993746>

In [11]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.log_prob(1)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.35676432>

In [12]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
print(batched_bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[2], event_shape=[], dtype=int32)


In [13]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.batch_shape

TensorShape([2])

In [14]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.sample(3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [0, 1],
       [0, 1]], dtype=int32)>

In [15]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.prob([1, 1])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.4, 0.5], dtype=float32)>

In [16]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.log_prob([1, 1])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.9162907, -0.6931472], dtype=float32)>

__Que__

In [17]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-0.8, 0., 1.9], scale=[1.25, 0.6, 2.8])
batched_normal.sample(2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-2.3344483 ,  0.22578081, -0.17660034],
       [-1.4268788 , -0.2955104 , -1.5213784 ]], dtype=float32)>

---

## __b) Multivariate distributions__

In [18]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
print(mv_normal)

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[], event_shape=[2], dtype=float32)


In [19]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
mv_normal.sample(3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.9036414 , -0.06948936],
       [ 0.18695807, -0.55958843],
       [-1.2047808 , -0.19340867]], dtype=float32)>

In [20]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
print(batched_normal)

tfp.distributions.Normal("Normal", batch_shape=[2], event_shape=[], dtype=float32)


In [21]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
batched_normal.sample(3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.24170399, -0.71748614],
       [-0.36169726,  1.9965515 ],
       [-1.2031542 ,  1.327983  ]], dtype=float32)>

`log_prob`

In [22]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
mv_normal.log_prob([0.2, -1.8])

<tf.Tensor: shape=(), dtype=float32, numpy=-4.1388974>

In [23]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
batched_normal.log_prob([0.2, -1.8])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.6389385, -2.499959 ], dtype=float32)>

__Batch Multivariate Distribution__

In [24]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[-1., 0.5],[2., 0], [-0.5, 1.5]],
    scale_diag=[[1., 1.5], [2., 0.5], [1., 1.]]
    )

print(batched_mv_normal)

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[3], event_shape=[2], dtype=float32)


__Sampling__

In [25]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[-1., 0.5],[2., 0], [-0.5, 1.5]],
    scale_diag=[[1., 1.5], [2., 0.5], [1., 1.]]
    )

batched_mv_normal.sample(2)

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[-1.2279872 ,  3.3174963 ],
        [ 0.19413948,  0.24735634],
        [-0.9016132 ,  1.6382647 ]],

       [[-1.4012393 ,  1.8286124 ],
        [ 1.1331738 ,  0.31065923],
        [-1.5911719 ,  0.79748106]]], dtype=float32)>

__Que__

In [26]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[0.3, 0.8, 1.1], [2.3, -0.3, -1.]], 
    scale_diag=[[1.5, 1., 0.4], [2.5, 1.5, 0.5]])

# Que: What is the shape of the Tensor returned by the following?
batched_mv_normal.log_prob([0., -1., 1.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -3.9172401, -11.917513 ], dtype=float32)>

## __c) The Independent distribution__

In [27]:
# Importing tensorflow probability library 
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
print(mv_normal)

'''
tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag",
                                          batch_shape=[],
                                          event_shape=[2],
                                          dtype=float32
                                          )
'''
batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
print(batched_normal)

'''
tfp.distributions.Normal("Normal",
                          batch_shape=[2],
                          event_shape=[],
                          dtype=float32
                          )
'''

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[], event_shape=[2], dtype=float32)
tfp.distributions.Normal("Normal", batch_shape=[2], event_shape=[], dtype=float32)


'\ntfp.distributions.Normal("Normal",\n                          batch_shape=[2],\n                          event_shape=[],\n                          dtype=float32\n                          )\n'

In [28]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])

independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims=1)
print(independent_normal)

tfp.distributions.Independent("IndependentNormal", batch_shape=[], event_shape=[2], dtype=float32)


In [29]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])

independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims=1)
independent_normal.log_prob([-0.2, 1.8])

<tf.Tensor: shape=(), dtype=float32, numpy=-2.9388976>

In [30]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[[-1., 0.5], [0., 1.], [0.3, -0.1]],
                            scale=[[1., 1.5], [0.2, 0.8], [2., 1.]])
print(batched_normal)

independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims=1)
print(independent_normal)

tfp.distributions.Normal("Normal", batch_shape=[3, 2], event_shape=[], dtype=float32)
tfp.distributions.Independent("IndependentNormal", batch_shape=[3], event_shape=[2], dtype=float32)


when `reinterpreted_batch_ndims=2`

In [31]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[[-1., 0.5], [0., 1.], [0.3, -0.1]],
                            scale=[[1., 1.5], [0.2, 0.8], [2., 1.]])
print(batched_normal)

independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims=2)
print(independent_normal)

tfp.distributions.Normal("Normal", batch_shape=[3, 2], event_shape=[], dtype=float32)
tfp.distributions.Independent("IndependentNormal", batch_shape=[], event_shape=[3, 2], dtype=float32)


__Question__

In [32]:
import numpy as np
import tensorflow_probability as tfp
tfd = tfp.distributions
	
probs = 0.5 * tf.ones((2, 4, 5))
dist = tfd.Independent(tfd.Bernoulli(probs=probs))
dist.log_prob(np.zeros((4, 5)))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-13.862944, -13.862944], dtype=float32)>

## __d) Sampling and log probs__

In [33]:
import tensorflow_probability as tfp
tfd = tfp.distributions

exp = tfd.Exponential(rate=[[1., 1.5, 0.8], [0.3, 0.4, 1.8]])
print(exp)

tfp.distributions.Exponential("Exponential", batch_shape=[2, 3], event_shape=[], dtype=float32)


In [34]:
import tensorflow_probability as tfp
tfd = tfp.distributions

exp = tfd.Exponential(rate=[[1., 1.5, 0.8], [0.3, 0.4, 1.8]])
ind_exp = tfd.Independent(exp)
print(ind_exp)

tfp.distributions.Independent("IndependentExponential", batch_shape=[2], event_shape=[3], dtype=float32)


In [35]:
import tensorflow_probability as tfp
tfd = tfp.distributions

exp = tfd.Exponential(rate=[[1., 1.5, 0.8], [0.3, 0.4, 1.8]])
ind_exp = tfd.Independent(exp)
ind_exp.sample(4)

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[1.0450152 , 0.5755661 , 0.57201266],
        [0.35571185, 2.9993176 , 1.3061632 ]],

       [[0.53088427, 0.8687641 , 0.9061054 ],
        [0.18346427, 3.114679  , 1.3135731 ]],

       [[0.43705982, 0.33043382, 1.0506781 ],
        [2.0970175 , 2.6761663 , 0.16461179]],

       [[0.03214772, 1.2576617 , 1.3908582 ],
        [3.9662836 , 1.4683392 , 0.01111567]]], dtype=float32)>

In [36]:
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
print(exp)
                 
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
print(ind_exp)

tfp.distributions.Exponential("Exponential", batch_shape=[2, 1, 2, 3], event_shape=[], dtype=float32)
tfp.distributions.Independent("IndependentExponential", batch_shape=[2, 1], event_shape=[2, 3], dtype=float32)


In [37]:
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)

ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
ind_exp.sample([4, 2])

<tf.Tensor: shape=(4, 2, 2, 1, 2, 3), dtype=float32, numpy=
array([[[[[[7.4250298e-03, 8.0979186e-01, 4.8355800e-01],
           [1.3371319e+00, 5.6241202e+00, 6.6637194e-01]]],


         [[[6.9196713e-01, 5.6891704e-01, 7.2674239e-01],
           [1.7746511e+00, 1.6127998e+00, 5.4522884e-01]]]],



        [[[[1.2235030e+00, 1.0835612e-01, 2.3766563e+00],
           [4.7605262e+00, 2.7098799e+00, 1.1755193e-01]]],


         [[[2.2834493e-01, 3.0178735e+00, 1.8308039e-01],
           [6.6000664e-01, 1.9622599e-01, 4.1256589e-01]]]]],




       [[[[[2.7563729e+00, 5.7837069e-01, 7.6256317e-01],
           [1.3326007e+00, 3.5093975e+00, 8.1236288e-02]]],


         [[[1.2270447e+00, 3.8814573e+00, 2.2289865e+00],
           [6.9758856e-01, 9.5233339e-01, 1.7990123e+00]]]],



        [[[[1.2468169e+00, 4.1401783e-01, 1.4839436e+00],
           [1.6757698e+00, 2.7027676e+00, 4.7308245e-01]]],


         [[[5.7193894e+00, 3.1797657e+00, 3.7911415e-01],
           [2.8926039e+00, 5.53656

In [38]:
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
                 
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
ind_exp.log_prob(0.5)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.2501554],
       [-5.3155975]], dtype=float32)>

In [39]:
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
                 
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
ind_exp.log_prob([[0.3, 0.5, 0.8]]) # Shape - (1, 3)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.7701554],
       [-5.885597 ]], dtype=float32)>

In [40]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
                 
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
ind_exp.log_prob(tf.random.uniform((5, 1, 1, 2, 1)))

<tf.Tensor: shape=(5, 2, 1), dtype=float32, numpy=
array([[[-6.9080343],
        [-7.333054 ]],

       [[-6.4038982],
        [-6.862806 ]],

       [[-6.4223037],
        [-6.8415303]],

       [[-4.29704  ],
        [-5.372185 ]],

       [[-6.05631  ],
        [-6.814649 ]]], dtype=float32)>

__Que__

In [41]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

loc = tf.zeros((2, 3, 1))
scale_diag = tf.ones(4)
dist = tfd.Independent(tfd.MultivariateNormalDiag(loc=loc, scale_diag=scale_diag))

dist.log_prob(tf.random.uniform((2, 1, 1, 4)))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-12.895037, -12.895037],
       [-13.7799  , -13.7799  ]], dtype=float32)>


## __e) Trainable distributions__



In [42]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=tf.Variable(0., name='loc'), scale=1.)
normal.trainable_variables

(<tf.Variable 'loc:0' shape=() dtype=float32, numpy=0.0>,)

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=tf.Variable(0., name='loc'), scale=1.)

def nll(x_train):  # Defining the negative log likelihood(nll)
    return -tf.reduce_mean(normal.log_prob(x_train))

'''
This function get_loss_and_grads takes a batch of training examples as an input
and computes the loss and gradients for our model.
'''
@tf.function
def get_loss_and_grads(x_train):
    with tf.GradientTape() as tape:
        tape.watch(normal.trainable_variables)
        loss = nll(x_train)
    grads = tape.gradient(loss, normal.trainable_variables)
    return loss, grads

optimizer = tf.keras.optimizers.SGD(learning_rate=0.05)

for _ in range(num_steps):
    loss, grads = get_loss_and_grads(x_samples)
    optimizer.apply_gradients(zip(grads, normal.trainable_variables))