<a href="https://colab.research.google.com/github/mohd-faizy/Probabilistic-Deep-Learning-with-TensorFlow/blob/main/00_The_TensorFlow_Probability_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

--- 
<strong> 
    <h1 align='center'>The TensorFlow Probability library</h1> 
</strong>

---

<p align='center'>
<a href=#></a></p>

<p align='center'>
  <a href="#"><img src='https://github.com/mohd-faizy/07T_Probabilistic-Deep-Learning-with-TensorFlow/blob/main/Tensorflow_Dev_png/head.png?raw=true' alt="head"></a>
</p>

In [1]:
# Importing tensorflow probability library 
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions


## __a) Univariate distributions__

In [2]:
# Importing tensorflow probability library 
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

# Defining our first univariate distribution object
'''
Standard normal distribution with 0 mean and standard
deviation equal to 1
'''
normal = tfd.Normal(loc=0., scale=1.)
print(normal)

tfp.distributions.Normal("Normal", batch_shape=[], event_shape=[], dtype=float32)


In [3]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=0., scale=1.)
normal.sample()

<tf.Tensor: shape=(), dtype=float32, numpy=0.79490465>

In [4]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=0., scale=1.)
normal.sample(3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.2895206 , 0.11389545, 1.8660847 ], dtype=float32)>

In [5]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=0., scale=1.)
normal.prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.35206532>

In [6]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=0., scale=1.)
normal.log_prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0439385>

In [7]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(probs=0.7)
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[], event_shape=[], dtype=int32)


In [8]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(logits=0.847)
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[], event_shape=[], dtype=int32)


In [9]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.sample(3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 1], dtype=int32)>

In [10]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.prob(1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.69993746>

In [11]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.log_prob(1)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.35676432>

In [12]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
print(batched_bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[2], event_shape=[], dtype=int32)


In [13]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.batch_shape

TensorShape([2])

In [14]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.sample(3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 0]], dtype=int32)>

In [15]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.prob([1, 1])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.4, 0.5], dtype=float32)>

In [16]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.log_prob([1, 1])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.9162907, -0.6931472], dtype=float32)>

__Que__

In [17]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-0.8, 0., 1.9], scale=[1.25, 0.6, 2.8])
batched_normal.sample(2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.60242516,  0.12748079,  0.5176313 ],
       [-1.0424016 , -1.037978  ,  4.0604763 ]], dtype=float32)>

---

## __b) Multivariate distributions__

In [18]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
print(mv_normal)

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[], event_shape=[2], dtype=float32)


In [19]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
mv_normal.sample(3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.73903275, -1.94632   ],
       [-0.652802  , -0.85901463],
       [-2.4864376 , -0.8765205 ]], dtype=float32)>

In [20]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
print(batched_normal)

tfp.distributions.Normal("Normal", batch_shape=[2], event_shape=[], dtype=float32)


In [21]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
batched_normal.sample(3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.6186607 ,  0.41333252],
       [-2.0201583 ,  1.5128474 ],
       [-3.4468193 ,  2.497111  ]], dtype=float32)>

`log_prob`

In [22]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
mv_normal.log_prob([0.2, -1.8])

<tf.Tensor: shape=(), dtype=float32, numpy=-4.1388974>

In [23]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
batched_normal.log_prob([0.2, -1.8])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.6389385, -2.499959 ], dtype=float32)>

__Batch Multivariate Distribution__

In [24]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[-1., 0.5],[2., 0], [-0.5, 1.5]],
    scale_diag=[[1., 1.5], [2., 0.5], [1., 1.]]
    )

print(batched_mv_normal)

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[3], event_shape=[2], dtype=float32)


__Sampling__

In [25]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[-1., 0.5],[2., 0], [-0.5, 1.5]],
    scale_diag=[[1., 1.5], [2., 0.5], [1., 1.]]
    )

batched_mv_normal.sample(2)

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[-2.127429  ,  1.0431628 ],
        [ 0.88582206,  0.47338235],
        [-2.2745285 ,  1.6040654 ]],

       [[ 1.1637785 ,  1.7076061 ],
        [ 2.4850268 ,  0.03935413],
        [ 0.25627726,  0.09590876]]], dtype=float32)>

__Que__

In [26]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[0.3, 0.8, 1.1], [2.3, -0.3, -1.]], 
    scale_diag=[[1.5, 1., 0.4], [2.5, 1.5, 0.5]])

# Que: What is the shape of the Tensor returned by the following?
batched_mv_normal.log_prob([0., -1., 1.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -3.9172401, -11.917513 ], dtype=float32)>

## __c) The Independent distribution__

In [27]:
# Importing tensorflow probability library 
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
print(mv_normal)

'''
tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag",
                                          batch_shape=[],
                                          event_shape=[2],
                                          dtype=float32
                                          )
'''
batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
print(batched_normal)

'''
tfp.distributions.Normal("Normal",
                          batch_shape=[2],
                          event_shape=[],
                          dtype=float32
                          )
'''

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[], event_shape=[2], dtype=float32)
tfp.distributions.Normal("Normal", batch_shape=[2], event_shape=[], dtype=float32)


'\ntfp.distributions.Normal("Normal",\n                          batch_shape=[2],\n                          event_shape=[],\n                          dtype=float32\n                          )\n'

In [28]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])

independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims=1)
print(independent_normal)

tfp.distributions.Independent("IndependentNormal", batch_shape=[], event_shape=[2], dtype=float32)


In [29]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])

independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims=1)
independent_normal.log_prob([-0.2, 1.8])

<tf.Tensor: shape=(), dtype=float32, numpy=-2.9388976>

In [30]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[[-1., 0.5], [0., 1.], [0.3, -0.1]],
                            scale=[[1., 1.5], [0.2, 0.8], [2., 1.]])
print(batched_normal)

independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims=1)
print(independent_normal)

tfp.distributions.Normal("Normal", batch_shape=[3, 2], event_shape=[], dtype=float32)
tfp.distributions.Independent("IndependentNormal", batch_shape=[3], event_shape=[2], dtype=float32)


when `reinterpreted_batch_ndims=2`

In [31]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

batched_normal = tfd.Normal(loc=[[-1., 0.5], [0., 1.], [0.3, -0.1]],
                            scale=[[1., 1.5], [0.2, 0.8], [2., 1.]])
print(batched_normal)

independent_normal = tfd.Independent(batched_normal, reinterpreted_batch_ndims=2)
print(independent_normal)

tfp.distributions.Normal("Normal", batch_shape=[3, 2], event_shape=[], dtype=float32)
tfp.distributions.Independent("IndependentNormal", batch_shape=[], event_shape=[3, 2], dtype=float32)


__Question__

In [32]:
import numpy as np
import tensorflow_probability as tfp
tfd = tfp.distributions
	
probs = 0.5 * tf.ones((2, 4, 5))
dist = tfd.Independent(tfd.Bernoulli(probs=probs))
dist.log_prob(np.zeros((4, 5)))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-13.862944, -13.862944], dtype=float32)>

## __d) Sampling and log probs__

In [33]:
import tensorflow_probability as tfp
tfd = tfp.distributions

exp = tfd.Exponential(rate=[[1., 1.5, 0.8], [0.3, 0.4, 1.8]])
print(exp)

tfp.distributions.Exponential("Exponential", batch_shape=[2, 3], event_shape=[], dtype=float32)


In [34]:
import tensorflow_probability as tfp
tfd = tfp.distributions

exp = tfd.Exponential(rate=[[1., 1.5, 0.8], [0.3, 0.4, 1.8]])
ind_exp = tfd.Independent(exp)
print(ind_exp)

tfp.distributions.Independent("IndependentExponential", batch_shape=[2], event_shape=[3], dtype=float32)


In [35]:
import tensorflow_probability as tfp
tfd = tfp.distributions

exp = tfd.Exponential(rate=[[1., 1.5, 0.8], [0.3, 0.4, 1.8]])
ind_exp = tfd.Independent(exp)
ind_exp.sample(4)

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[1.2077969 , 0.3564397 , 0.14139712],
        [1.9054649 , 0.49919507, 0.10692663]],

       [[0.55449593, 1.8828753 , 0.9477952 ],
        [2.1203556 , 0.6551066 , 0.007934  ]],

       [[0.99103814, 0.4720573 , 6.0971665 ],
        [2.8822787 , 0.8126075 , 2.4295464 ]],

       [[0.04863515, 0.25530922, 5.282557  ],
        [3.6649277 , 1.7710142 , 1.6327673 ]]], dtype=float32)>

In [36]:
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
print(exp)
                 
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
print(ind_exp)

tfp.distributions.Exponential("Exponential", batch_shape=[2, 1, 2, 3], event_shape=[], dtype=float32)
tfp.distributions.Independent("IndependentExponential", batch_shape=[2, 1], event_shape=[2, 3], dtype=float32)


In [37]:
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)

ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
ind_exp.sample([4, 2])

<tf.Tensor: shape=(4, 2, 2, 1, 2, 3), dtype=float32, numpy=
array([[[[[[1.2257264e+00, 1.2232832e+00, 7.0149720e-01],
           [8.3357973e+00, 1.4403078e-01, 1.0633538e+00]]],


         [[[9.3659365e-01, 3.4003446e+00, 1.6902207e-01],
           [1.0873689e+01, 2.9064640e-01, 5.1067572e+00]]]],



        [[[[6.7949313e-01, 1.9284557e-01, 9.8037654e-01],
           [2.6039395e-01, 1.1054556e+00, 8.9554620e-01]]],


         [[[4.3894925e+00, 6.8220401e-01, 3.5020402e-01],
           [1.5494161e-02, 1.9892679e+00, 2.8934154e-01]]]]],




       [[[[[2.9557282e-01, 1.8762451e-01, 1.2875540e+00],
           [3.3995662e+00, 1.8804076e+00, 3.4813628e-01]]],


         [[[3.1175594e+00, 9.5878847e-02, 3.1018755e-01],
           [1.2379711e+00, 1.5009018e+00, 8.9787644e-01]]]],



        [[[[1.0001349e-01, 1.7494854e+00, 2.6508400e+00],
           [5.1811051e-01, 1.6986041e+00, 2.0863959e-01]]],


         [[[1.0381411e+00, 2.5614121e+00, 9.7171915e-01],
           [2.3956754e+00, 6.81608

In [38]:
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
                 
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
ind_exp.log_prob(0.5)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.2501554],
       [-5.3155975]], dtype=float32)>

In [39]:
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
                 
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
ind_exp.log_prob([[0.3, 0.5, 0.8]]) # Shape - (1, 3)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.7701554],
       [-5.885597 ]], dtype=float32)>

In [40]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

rates = [
        [[[1., 1.5, 0.8], [0.3, 0.4, 1.8]]],
        [[[0.2, 0.4, 1.4], [0.4, 1.1, 0.9]]]
]

exp = tfd.Exponential(rate=rates)
                 
ind_exp = tfd.Independent(exp, reinterpreted_batch_ndims=2)
ind_exp.log_prob(tf.random.uniform((5, 1, 1, 2, 1)))

<tf.Tensor: shape=(5, 2, 1), dtype=float32, numpy=
array([[[-4.3231053],
        [-5.252756 ]],

       [[-4.4710703],
        [-5.109299 ]],

       [[-3.4200592],
        [-5.0796127]],

       [[-2.0246203],
        [-3.5274224]],

       [[-5.9949427],
        [-6.746994 ]]], dtype=float32)>

__Que__

In [41]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

loc = tf.zeros((2, 3, 1))
scale_diag = tf.ones(4)
dist = tfd.Independent(tfd.MultivariateNormalDiag(loc=loc, scale_diag=scale_diag))

dist.log_prob(tf.random.uniform((2, 1, 1, 4)))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-12.56535 , -12.56535 ],
       [-13.465539, -13.465539]], dtype=float32)>


## __e) Trainable distributions__



In [42]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=tf.Variable(0., name='loc'), scale=1.)
normal.trainable_variables

(<tf.Variable 'loc:0' shape=() dtype=float32, numpy=0.0>,)

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

normal = tfd.Normal(loc=tf.Variable(0., name='loc'), scale=1.)

def nll(x_train):
    return -tf.reduce_mean(normal.log_prob(x_train))

'''
This function get_loss_and_grads takes a batch of training examples as an input
and computes the loss and gradients for our model.
'''
@tf.function
def get_loss_and_grads(x_train):
    with tf.GradientTape() as tape:
        tape.watch(normal.trainable_variables)
        loss = nll(x_train)
    grads = tape.Gradient(loss, normal.trainable_variables)
    return loss, grads

optimizer = tf.keras.optimizers.SGD(learning_rate=0.05)

for _ in range(num_steps):
    loss, grads = get_loss_and_grads(x_samples)
    optimizer.apply_gradient(zip(grads, normal.trainable_variables))