<a href="https://colab.research.google.com/github/mohd-faizy/07T_Probabilistic-Deep-Learning-with-TensorFlow/blob/main/00_The_TensorFlow_Probability_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

--- 
<strong> 
    <h1 align='center'>The TensorFlow Probability library</h1> 
</strong>

---

<p align='center'>
<a href=#></a></p>

<p align='center'>
  <a href="#"><img src='https://github.com/mohd-faizy/07T_Probabilistic-Deep-Learning-with-TensorFlow/blob/main/Tensorflow_Dev_png/head.png?raw=true' alt="head"></a>
</p>

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions    # Shortcut to the distributions

## __a) Univariate distributions__

In [2]:
# Defining our first univariate distribution object
'''
Standard normal distribution with 0 mean and standard
deviation equal to 1
'''
normal = tfd.Normal(loc=0., scale=1.)
print(normal)

tfp.distributions.Normal("Normal", batch_shape=[], event_shape=[], dtype=float32)


In [3]:
normal = tfd.Normal(loc=0., scale=1.)
normal.sample()

<tf.Tensor: shape=(), dtype=float32, numpy=0.6135887>

In [4]:
normal = tfd.Normal(loc=0., scale=1.)
normal.sample(3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.75087655, -1.7904053 ,  1.6093224 ], dtype=float32)>

In [5]:
normal = tfd.Normal(loc=0., scale=1.)
normal.prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.35206532>

In [6]:
normal = tfd.Normal(loc=0., scale=1.)
normal.log_prob(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0439385>

In [7]:
bernoulli = tfd.Bernoulli(probs=0.7)
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[], event_shape=[], dtype=int32)


In [8]:
bernoulli = tfd.Bernoulli(logits=0.847)
print(bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[], event_shape=[], dtype=int32)


In [9]:
bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.sample(3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 1], dtype=int32)>

In [10]:
bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.prob(1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.69993746>

In [11]:
bernoulli = tfd.Bernoulli(logits=0.847)
bernoulli.log_prob(1)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.35676432>

In [12]:
batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
print(batched_bernoulli)

tfp.distributions.Bernoulli("Bernoulli", batch_shape=[2], event_shape=[], dtype=int32)


In [13]:
batched_bernoulli.batch_shape

TensorShape([2])

In [14]:
batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.sample(3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [1, 0],
       [1, 0]], dtype=int32)>

In [15]:
batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.prob([1, 1])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.4, 0.5], dtype=float32)>

In [16]:
batched_bernoulli = tfd.Bernoulli(probs=[0.4, 0.5])
batched_bernoulli.log_prob([1, 1])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.9162907, -0.6931472], dtype=float32)>

__Que__

In [17]:
batched_normal = tfd.Normal(loc=[-0.8, 0., 1.9], scale=[1.25, 0.6, 2.8])
batched_normal.sample(2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-2.2298453 , -0.35056382, -1.9923555 ],
       [-1.0445325 ,  0.04784699,  2.2386587 ]], dtype=float32)>

---

## __b) Multivariate distributions__

In [18]:
mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
print(mv_normal)

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[], event_shape=[2], dtype=float32)


In [19]:
mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
mv_normal.sample(3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.621851  , -0.18090868],
       [-2.1831627 ,  1.7473242 ],
       [-1.2249209 ,  2.4647455 ]], dtype=float32)>

In [20]:
batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
print(batched_normal)

tfp.distributions.Normal("Normal", batch_shape=[2], event_shape=[], dtype=float32)


In [21]:
batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
batched_normal.sample(3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7395121 ,  2.9275239 ],
       [-0.62652946, -1.22621   ],
       [-1.2752295 , -0.09043896]], dtype=float32)>

`log_prob`

In [22]:
mv_normal = tfd.MultivariateNormalDiag(loc=[-1., 0.5], scale_diag=[1., 1.5])
mv_normal.log_prob([0.2, -1.8])

<tf.Tensor: shape=(), dtype=float32, numpy=-4.1388974>

In [23]:
batched_normal = tfd.Normal(loc=[-1., 0.5], scale=[1., 1.5])
batched_normal.log_prob([0.2, -1.8])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.6389385, -2.499959 ], dtype=float32)>

__Batch Multivariate Distribution__

In [24]:
batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[-1., 0.5],[2., 0], [-0.5, 1.5]],
    scale_diag=[[1., 1.5], [2., 0.5], [1., 1.]]
    )

print(batched_mv_normal)

tfp.distributions.MultivariateNormalDiag("MultivariateNormalDiag", batch_shape=[3], event_shape=[2], dtype=float32)


__Sampling__

In [25]:
batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[-1., 0.5],[2., 0], [-0.5, 1.5]],
    scale_diag=[[1., 1.5], [2., 0.5], [1., 1.]]
    )

batched_mv_normal.sample(2)

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[-0.527969  , -0.8762783 ],
        [ 0.1737796 ,  0.16743484],
        [ 0.6628307 ,  1.5791364 ]],

       [[-2.5523376 ,  1.2221279 ],
        [ 1.318002  ,  0.177484  ],
        [-1.5138515 ,  1.8052024 ]]], dtype=float32)>

__Que__

In [26]:
batched_mv_normal = tfd.MultivariateNormalDiag(
    loc=[[0.3, 0.8, 1.1], [2.3, -0.3, -1.]], 
    scale_diag=[[1.5, 1., 0.4], [2.5, 1.5, 0.5]])

# Que: What is the shape of the Tensor returned by the following?
batched_mv_normal.log_prob([0., -1., 1.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -3.9172401, -11.917513 ], dtype=float32)>

## __c) The Independent distribution__

## __d) Sampling and log probs__


## __e) Trainable distributions__

